[env]
MAIN_CLASS = "dev.ekuinox.miharu.Miharu"
OUTPUT_FILE = "Miharu.jar"

[tasks.build]
command = "scala-cli"
args = [
    "--power",
    "package",
    "--assembly",
    ".",
    "--main-class",
    "${MAIN_CLASS}",
    "--force",
    "-o",
    "${OUTPUT_FILE}",
]
